package me.kerooker.rpgnpcgenerator.ui.theme

import androidx.compose.ui.graphics.Color

// Brand-derived tonal palette. Seeded from the historical brand blue (#24A5F1) with a pink accent
// (#D81B60) carried into the tertiary role.

val LightPrimary = Color(0xFF00639B)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFCEE5FF)
val LightOnPrimaryContainer = Color(0xFF001D33)
val LightSecondary = Color(0xFF50606E)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD3E5F5)
val LightOnSecondaryContainer = Color(0xFF0C1D29)
val LightTertiary = Color(0xFFB90063)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFD9E2)
val LightOnTertiaryContainer = Color(0xFF3E001D)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFCFCFF)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFFCFCFF)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFDEE3EB)
val LightOnSurfaceVariant = Color(0xFF42474E)
val LightOutline = Color(0xFF72777F)

val DarkPrimary = Color(0xFF97CBFF)
val DarkOnPrimary = Color(0xFF003354)
val DarkPrimaryContainer = Color(0xFF004A77)
val DarkOnPrimaryContainer = Color(0xFFCEE5FF)
val DarkSecondary = Color(0xFFB7C9D9)
val DarkOnSecondary = Color(0xFF22323F)
val DarkSecondaryContainer = Color(0xFF384956)
val DarkOnSecondaryContainer = Color(0xFFD3E5F5)
val DarkTertiary = Color(0xFFFFB1C8)
val DarkOnTertiary = Color(0xFF650033)
val DarkTertiaryContainer = Color(0xFF8E004A)
val DarkOnTertiaryContainer = Color(0xFFFFD9E2)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1A1C1E)
val DarkOnBackground = Color(0xFFE2E2E6)
val DarkSurface = Color(0xFF1A1C1E)
val DarkOnSurface = Color(0xFFE2E2E6)
val DarkSurfaceVariant = Color(0xFF42474E)
val DarkOnSurfaceVariant = Color(0xFFC2C7CF)
val DarkOutline = Color(0xFF8C9199)
